### ISSUE TITLE
Вопрос / Question

### ISSUE THREAD

**Issue by KotikNekot** [Kolyakot33/foxy-bot#2]
Где мои арбузы? / Where are my watermelons?

**Comment by Kolyakot33** [comment]
Здравствуйте. Какие именно арбузы вы ищите?

**Comment by KotikNekot** [comment]
> Они тут: [watermelons](https://github.com/Kolyakot33/foxy-bot/tree/watermelons)

спасибо большое, я думал мне гг от мамы

**Comment by INotSleep** [comment]
Что они там забыли
